### ISSUE TITLE
Few errors that prevent running the project

### ISSUE THREAD

**Issue by Tyldar** [electroneum/electroneum-pool#1]
After installing the whole source, puting config.json etc.. nothing is starting : 

> Failed to read config file config.json
> 
> SyntaxError: Unexpected token /
> 
> /home/ubuntu/electroneum-pool/lib/logger.js:16
> var logDir = config.logging.files.directory;
>              ^
> ReferenceError: config is not defined
>     at Object.<anonymous> (/home/ubuntu/electroneum-pool/lib/logger.js:16:14)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/ubuntu/electroneum-pool/init.js:10:1)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)

**Comment by Tyldar** [comment]
It seems that the json in the readme is not correct syntax :)
