### ISSUE TITLE
I CAN NOT INITIAL A POOL node init.js ERROR

### ISSUE THREAD

**Issue by guilassj** [electroneum/electroneum-pool#106]
I FOLLOWED ALL TUTORIAL STEPS MORE WHEN I CAME IN STEP 5) Start the pool, I GET ONE ERROR:
guilas@ubuntu:~/electroneum-pool$ node init.js
module.js:557
    throw err;
    ^

Error: Cannot find module 'redis'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/guilas/electroneum-pool/init.js:5:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by guilassj** [comment]
I WAS INSTALLING DEPENDENCIES WITH NPM INSTALL REDIS ... NOW I RECEIVE ANOTHER ERROR:
Error: Cannot find module 'multi-hashing'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/guilas/electroneum-pool/lib/pool.js:7:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
2017-12-18 19:03:36 [master] Pool fork 1 died, spawning replacement worker...

**Comment by guilassj** [comment]
I GOT TO HAVE SOME PROGRESS, BUT I HAVE MORE ERRORS WHEN EXECUTING NODE INIT.JS:
2017-12-18 19:35:41 [master] Pool fork 1 died, spawning replacement worker...
module.js:689
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/guilas/electroneum-pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

**Comment by Cryp70n1cArmy** [comment]
Can you type node -v and send the output version. I find that v-.10.25 is the only one that works perfectly without any issues. 

Firstly run:

nvm install 0.10.25

then

nvm use 0.10.25

then

node -v and send me the output. You should

**Comment by guilassj** [comment]
Thank you, my swimming pool is already on the network.
