### ISSUE TITLE
Cannot find module bignum.node

### ISSUE THREAD

**Issue by TobCar** [electroneum/electroneum-pool#12]
Hello I've installed all the requirements as the ReadMe states but I get this error when I try to run the pool:

Error: Cannot find module '/electroneum-pool/node_modules/bignum/binding/bignum.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/electroneum-pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
2017-11-03 00:45:50 [master] Pool fork 1 died, spawning replacement worker..

Here is my config file:
```
{
    "coin": "electroneum",
    "symbol": "ETN",
    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },

        "console": {
            "level": "info",
            "colors": true
        }
    },
    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "[Omit for GitHub]",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "lastBlockCheckRate": 1
        }
    },
    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 10,
        "mixin": 0,
        "transferFee": 1,
        "minPayment": 10000,
        "denomination": 100
    },
    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 20,
        "poolFee": 1.8,
        "devDonation": 0.1,
        "coreDevDonation": 0.1
    },
    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 3,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "test"
    },
    "daemon": {
        "host": "127.0.0.1",
        "port": 18081
    },
    "wallet": {
        "host": "127.0.0.1",
        "port": 8082
    },
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": "[omit for GitHub]"
    }
}
```

Any ideas?

**Comment by TobCar** [comment]
I had to uninstall NodeJS then reinstalled it to make sure I had v0.10.48.
Once that was done, I ran "npm update" and "apt-get install bignum" since it wasn't installed by npm.

**Comment by electroneumRepo** [comment]
I recommend installing node version manager. This allows you to easily install other version of node.
