### ISSUE TITLE
Error on running node init.js

### ISSUE THREAD

**Issue by sudeepb02** [electroneum/electroneum-pool#123]
I'm trying to set up my own pool but getting the following error on running `node init.js`

```
root@ubuntu-etn:~/pool# node init.js
2017-12-27 15:08:58 [master] Pool spawned on 1 thread(s)
2017-12-27 15:09:01 [payments] Started
2017-12-27 15:09:01 [unlocker] Started
2017-12-27 15:09:02 [payments] No workers' balances reached the minimum payment threshold
2017-12-27 15:09:02 [unlocker] No blocks candidates in redis
2017-12-27 15:09:02 [api] API started & listening on port 8117
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
2017-12-27 15:09:02 [master] Pool fork 1 died, spawning replacement worker...
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
2017-12-27 15:09:05 [master] Pool fork 1 died, spawning replacement worker...
^C
root@ubuntu-etn:~/pool# 
```

Maybe the error is in the startup script as the api module fails. The following is my config file :

```

    "coin": "electroneum",
    "symbol": "ETN",
    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },

        "console": {
            "level": "info",
            "colors": true
        }
    },
    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "etnkQaLwmrMfL2a26vFPvHTD1iFHS7y6pYNJAGPHTDdZaY8viEPqtgvZz44KuyN3iJFpfJTSik1XJ6PT68DJCHNW4VzzGYJ8B6",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "lastBlockCheckRate": 1
        }
    },
    "payments": {
        "enabled": true,
        "interval": 60,
        "maxAddresses": 10,
        "mixin": 0,
        "transferFee": 1,
        "minPayment": 5000,
        "denomination": 100
    },
    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 20,
        "poolFee": 2,
        "devDonation": 0,
        "coreDevDonation": 0
    },
    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 3,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "test"
    },
    "daemon": {
        "host": "127.0.0.1",
        "port": 26968
    },
    "wallet": {
        "host": "127.0.0.1",
        "port": 26969
    },
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null
    }
}
```

**Comment by electroneumRepo** [comment]
Please confirm what version of node are you using.

**Comment by sudeepb02** [comment]
v4.2.6

**Comment by sudeepb02** [comment]
@electroneumRepo I also trie installing and running v0.10.48

**Comment by electroneumRepo** [comment]
You need to be running node 0.10.48.

It won't work if your running a different version

**Comment by electroneumRepo** [comment]
Closing due to inactivity
