### ISSUE TITLE
Pool fork 2 died when trying to run init.js

### ISSUE THREAD

**Issue by bbengt1** [electroneum/electroneum-pool#144]
This is the error I am getting with I try to start init.js

```
Error: /home/brent/pool/node_modules/bignum/binding/bignum.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/brent/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
2018-01-07 20:21:27 [master] Pool fork 2 died, spawning replacement worker...
2018-01-07 20:21:27 [api] Stat collection finished: 4 ms redis, 7 ms daemon
2018-01-07 20:21:27 [api] Broadcasting to 0 visitors and 0 address lookups
```

Thanks ahead of time for any assistance.

**Comment by electroneumRepo** [comment]
Please can you confirm which version of node you are using.

Also what OS?

Have you installed all dependencies and followed instructions as described in the README file?

**Comment by bbengt1** [comment]
looks like I am using node v4.2.6
running on unbuntu 16.04.3

**Comment by bet0x** [comment]
You need to follow the instructions on both guides but follow the reqs of this one. Your node version is incorrect.

**Comment by bbengt1** [comment]
I rebuild the sever and was able to get it working correctly. Thank you all for the assistance.

**Comment by AMatiasC** [comment]
Hi! i have the same error:


 module.js:328
    throw err;
    ^

Error: Cannot find module 'bignum'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/etn.pool/lib/pool.js:6:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
2018-01-10 14:33:47 [master] Pool fork 1 died, spawning replacement worker...
module.js:328
    throw err;
    ^

and i have the all dependencies installed and i use nvm 0.10.48. Whats wrong?

**Comment by bet0x** [comment]
If you are running this under root you are doing it wrong. Don't run the pool with root. I had the same error when i did it like that. Check for ports to match too.
