### ISSUE TITLE
Pool fork 2 died when trying to run init.js

### ISSUE THREAD

**Issue by AMatiasC** [electroneum/electroneum-pool#150]
Hi Guys! i have the error: 
error: Cannot find module 'bignum'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/etn.pool/lib/pool.js:6:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
2018-01-10 14:33:47 [master] Pool fork 1 died, spawning replacement worker...
module.js:328
    throw err;
    ^

I have installed all dependencies and i'am using nvm 0.10.48. 
Please,i need your help/
Thanks,

Regards.

**Comment by electroneumRepo** [comment]
It seems that one of the modules has not been installed correctly.

Can you confirm that when your ran `npm install` there were no errors?

**Comment by Crypto-Max** [comment]
Agreed with Richard’s answer.. what I did to fix this issue was reinstall all dependecies but I would write (nvm use 0.10.48) in my terminal before installing one by one the dependecies.

The problem is because you are installing the dependecies with a different node version. Just make sure to use nvm 0.10.48 .... there is also a command to set default to 0.10.48 if you set that and restart terminal it should automatically use the right node version.
