### ISSUE TITLE
npm ERR! cryptonote-util@0.0.3 install: fails at `node-gyp rebuild`

### ISSUE THREAD

**Issue by PCPisChill** [electroneum/electroneum-pool#202]
**Latest:**
```
make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory '/var/www/elec/pool2/node_modules/multi-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/elecUsr/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.14.32-xxxx-grs-ipv6-64
gyp ERR! command "/home/elecUsr/.nvm/versions/node/v9.4.0/bin/node" "/home/elecUsr/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/elec/pool2/node_modules/multi-hashing
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/elecUsr/.npm/_logs/2018-01-28T04_44_02_558Z-debug.log
$ node -v
v9.4.0
```

**0.10.48:**
```
make: Leaving directory '/var/www/elec/pool2/node_modules/multi-hashing/build'
multi-hashing@0.0.9 node_modules/multi-hashing
└── bindings@1.3.0
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/elecUsr/.nvm/v0.10.48/bin/node" "/home/elecUsr/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/elec/pool2/npm-debug.log
```

I'm using Debian 9 Stretch, I've tried node 0.10.0, 0.10.28, 0.10.29, 0.10.48, 0.12.18, 9.4.0, and tried different packages of cryptonote-util all with the same result.

This pool is using Debian, so it doesn't seem like that's the issue: http://electroneumpool.pw/

Edit: Fixed the issue by switching to a ubuntu server, but I had similar errors before I installed all the dependencies so I was probably missing a dependency on debian.

**Comment by electroneumRepo** [comment]
Please check and ensure that you have all the dependencies installed, I've not personally tested on Debian so cannot help with getting it running on Debian.
