### ISSUE TITLE
npm ERR! cryptonote-util@0.0.3 install: fails at `node-gyp rebuild`

### ISSUE THREAD

**Issue by workboy** [electroneum/electroneum-pool#210]
in nvm V0.10.29 
user : Root
make: Leaving directory '/pool/node_modules/multi-hashing/build'
npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.3 install script.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.0-105-generic
npm ERR! command "/.nvm/v0.10.29/bin/node" "/.nvm/v0.10.29/bin/npm" "update"
npm ERR! cwd /pool
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
multi-hashing@0.0.9 node_modules/multi-hashing
└── bindings@1.3.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /pool/npm-debug.log
npm ERR! not ok code 0

in nvm V0.10.48
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-105-generic
gyp ERR! command "node" "/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.4.0-105-generic
npm ERR! argv "/.nvm/v0.10.48/bin/node" "/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /pool/npm-debug.log

not root 
npm ERR! tar.unpack untar error /home/pool/.npm/cryptonote-util/0.0.3/package.tgz
npm ERR! Linux 4.4.0-105-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! path /pool/node_modules/cryptonote-util
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/pool/node_modules/cryptonote-util'
npm ERR!  { [Error: EACCES, mkdir '/pool/node_modules/cryptonote-util']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/pool/node_modules/cryptonote-util',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/pool/node_modules/cryptonote-util',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/pool/node_modules/multi-hashing'
npm ERR! error rolling back  { [Error: EACCES, rmdir '/pool/node_modules/multi-hashing']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/pool/node_modules/multi-hashing' }
npm ERR! Linux 4.4.0-105-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! path npm-debug.log.2950469391
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, open 'npm-debug.log.2950469391'
npm ERR!  { [Error: EACCES, open 'npm-debug.log.2950469391'] errno: 3, code: 'EACCES', path: 'npm-debug.log.2950469391' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /pool/npm-debug.log

I've tried all the solutions that I've collected at the moment, but I can't install it, help!

**Comment by electroneumRepo** [comment]
What OS are you using?

**Comment by workboy** [comment]
ubuntu 16.04 
now I'm trying 14.04

**Comment by electroneumRepo** [comment]
We recommend 16.04

Can you confirm you have installed the required dependencies?

**Comment by workboy** [comment]
Now I'm not sure. Because I've erased my last system

**Comment by gregryman** [comment]
I'm having the same issue. After cloning the repo I run 'npm update' and it fails to install the deps.

greg@pool:~/pool$ npm update
-
> cryptonote-util@0.0.3 install /home/greg/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/home/greg/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
In file included from ../node_modules/nan/nan.h:199:0,
                 from ../src/main.cc:15:
../node_modules/nan/nan_maybe_pre_43_inl.h: In function ‘Nan::Maybe<bool> Nan::DefineOwnProperty(v8::Handle<v8::Object>, v8::Handle<v8::String>, v8::Handle<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_pre_43_inl.h:158:44: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
                  !(current & v8::ReadOnly) &&               // writable AND
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      !((attribs ^ current) & ~v8::ReadOnly) // same excluding RO
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<unnamed struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:111: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/greg/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/greg/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.13.0-16-generic
gyp ERR! command "node" "/home/greg/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/greg/pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> multi-hashing@0.0.9 install /home/greg/pool/node_modules/multi-hashing
> node-gyp rebuild

make: Entering directory '/home/greg/pool/node_modules/multi-hashing/build'
  CXX(target) Release/obj.target/multihashing/multihashing.o
../multihashing.cc:23:22: warning: extra tokens at end of #include directive
     #include "sha1.h",
                      ^
../multihashing.cc: In function ‘v8::Handle<v8::Value> boolberry(const v8::Arguments&)’:
../multihashing.cc:470:7: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
     if(args.Length() >= 3)
       ^
  CC(target) Release/obj.target/multihashing/scryptjane.o
In file included from ../scryptjane/scrypt-jane-portable.h:280:0,
                 from ../scryptjane.c:10:
../scryptjane/scrypt-jane-portable-x86.h: In function ‘detect_cpu’:
../scryptjane/scrypt-jane-portable-x86.h:275:18: warning: variable ‘vendor’ set but not used [-Wunused-but-set-variable]
  cpu_vendors_x86 vendor = cpu_nobody;
                  ^~~~~~
In file included from ../scryptjane/scrypt-jane-chacha.h:12:0,
                 from ../scryptjane/scrypt-jane-romix.h:2,
                 from ../scryptjane.c:12:
At top level:
../scryptjane/scrypt-jane-romix-basic.h:65:1: warning: ‘scrypt_block’ defined but not used [-Wunused-function]
 scrypt_block(scrypt_mix_word_t *base, scrypt_mix_word_t i) {
 ^~~~~~~~~~~~
../scryptjane/scrypt-jane-romix-basic.h:13:1: warning: ‘scrypt_romix_convert_endian’ defined but not used [-Wunused-function]
 scrypt_romix_convert_endian(scrypt_mix_word_t *blocks, size_t nblocks) {
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/multihashing/scryptn.o
  CC(target) Release/obj.target/multihashing/keccak.o
  CC(target) Release/obj.target/multihashing/skein.o
In file included from ../skein.c:8:0:
../sha256.h:390:1: warning: ‘PBKDF2_SHA256’ defined but not used [-Wunused-function]
 PBKDF2_SHA256(const uint8_t * passwd, size_t passwdlen, const uint8_t * salt,
 ^~~~~~~~~~~~~
  CC(target) Release/obj.target/multihashing/x11.o
  CC(target) Release/obj.target/multihashing/quark.o
../quark.c:101:1: warning: ‘be32dec_vect’ defined but not used [-Wunused-function]
 be32dec_vect(uint32_t *dst, const unsigned char *src, uint32_t len)
 ^~~~~~~~~~~~
../quark.c:88:1: warning: ‘be32enc_vect’ defined but not used [-Wunused-function]
 be32enc_vect(unsigned char *dst, const uint32_t *src, uint32_t len)
 ^~~~~~~~~~~~
  CC(target) Release/obj.target/multihashing/bcrypt.o
  CC(target) Release/obj.target/multihashing/groestl.o
In file included from ../groestl.c:8:0:
../sha256.h:390:1: warning: ‘PBKDF2_SHA256’ defined but not used [-Wunused-function]
 PBKDF2_SHA256(const uint8_t * passwd, size_t passwdlen, const uint8_t * salt,
 ^~~~~~~~~~~~~
  CC(target) Release/obj.target/multihashing/blake.o
  CC(target) Release/obj.target/multihashing/fugue.o
  CC(target) Release/obj.target/multihashing/qubit.o
  CC(target) Release/obj.target/multihashing/hefty1.o
In file included from ../hefty1.c:7:0:
../sha256.h:390:1: warning: ‘PBKDF2_SHA256’ defined but not used [-Wunused-function]
 PBKDF2_SHA256(const uint8_t * passwd, size_t passwdlen, const uint8_t * salt,
 ^~~~~~~~~~~~~
  CC(target) Release/obj.target/multihashing/shavite3.o
  CC(target) Release/obj.target/multihashing/cryptonight.o
../cryptonight.c:92:13: warning: ‘swap_blocks’ defined but not used [-Wunused-function]
 static void swap_blocks(uint8_t* a, uint8_t* b) {
             ^~~~~~~~~~~
../cryptonight.c:74:13: warning: ‘sum_half_blocks’ defined but not used [-Wunused-function]
 static void sum_half_blocks(uint8_t* a, const uint8_t* b) {
             ^~~~~~~~~~~~~~~
../cryptonight.c:60:13: warning: ‘mul’ defined but not used [-Wunused-function]
 static void mul(const uint8_t* a, const uint8_t* b, uint8_t* res) {
             ^~~
  CC(target) Release/obj.target/multihashing/x13.o
  CXX(target) Release/obj.target/multihashing/boolberry.o
In file included from ../crypto/cryptonote_core/cryptonote_format_utils.h:7:0,
                 from ../boolberry.cc:2:
../crypto/cryptonote_core/../wild_keccak.h: In function ‘int crypto::keccak_generic(const uint8_t*, size_t, uint8_t*, size_t)’:
../crypto/cryptonote_core/../wild_keccak.h:63:39: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
     rsiz = sizeof(state_t_m) == mdlen ? HASH_DATA_AREA : 200 - 2 * mdlen;
                  ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../crypto/cryptonote_core/../wild_keccak.h: In function ‘int crypto::wild_keccak(const uint8_t*, size_t, uint8_t*, size_t, callback_t)’:
../crypto/cryptonote_core/../wild_keccak.h:98:39: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
     rsiz = sizeof(state_t_m) == mdlen ? HASH_DATA_AREA : 200 - 2 * mdlen;
                  ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../crypto/cryptonote_core/../wild_keccak.h: In instantiation of ‘int crypto::wild_keccak(const uint8_t*, size_t, uint8_t*, size_t, callback_t) [with f_traits = crypto::mul_f; callback_t = cryptonote::get_blob_longhash_bb(const blobdata&, crypto::hash&, uint64_t, callback_t) [with callback_t = boolberry_hash(const char*, uint32_t, const char*, uint64_t, char*, uint64_t)::<lambda(uint64_t)>; blobdata = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]::<lambda(uint64_t (&)[25], uint64_t (&)[24])>; uint8_t = unsigned char; size_t = long unsigned int]’:
../crypto/cryptonote_core/../wild_keccak.h:151:26:   required from ‘int crypto::wild_keccak_dbl(const uint8_t*, size_t, uint8_t*, size_t, callback_t) [with f_traits = crypto::mul_f; callback_t = cryptonote::get_blob_longhash_bb(const blobdata&, crypto::hash&, uint64_t, callback_t) [with callback_t = boolberry_hash(const char*, uint32_t, const char*, uint64_t, char*, uint64_t)::<lambda(uint64_t)>; blobdata = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]::<lambda(uint64_t (&)[25], uint64_t (&)[24])>; uint8_t = unsigned char; size_t = long unsigned int]’
../crypto/cryptonote_core/cryptonote_format_utils.h:15:43:   required from ‘bool cryptonote::get_blob_longhash_bb(const blobdata&, crypto::hash&, uint64_t, callback_t) [with callback_t = boolberry_hash(const char*, uint32_t, const char*, uint64_t, char*, uint64_t)::<lambda(uint64_t)>; blobdata = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]’
../boolberry.cc:10:6:   required from here
cc1plus: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
  CC(target) Release/obj.target/multihashing/nist5.o
  CC(target) Release/obj.target/multihashing/sha1.o
  CC(target) Release/obj.target/multihashing/x15.o
  CC(target) Release/obj.target/multihashing/fresh.o
  CC(target) Release/obj.target/multihashing/sha3/sph_hefty1.o
  CC(target) Release/obj.target/multihashing/sha3/sph_fugue.o
  CC(target) Release/obj.target/multihashing/sha3/aes_helper.o
../sha3/aes_helper.c:90:19: warning: ‘AES3_LE’ defined but not used [-Wunused-const-variable=]
 #define AES3      AES3_LE
                   ^
../sha3/aes_helper.c:323:22: note: in expansion of macro ‘AES3’
 static const sph_u32 AES3[256] = {
                      ^~~~
../sha3/aes_helper.c:89:19: warning: ‘AES2_LE’ defined but not used [-Wunused-const-variable=]
 #define AES2      AES2_LE
                   ^
../sha3/aes_helper.c:256:22: note: in expansion of macro ‘AES2’
 static const sph_u32 AES2[256] = {
                      ^~~~
../sha3/aes_helper.c:88:19: warning: ‘AES1_LE’ defined but not used [-Wunused-const-variable=]
 #define AES1      AES1_LE
                   ^
../sha3/aes_helper.c:189:22: note: in expansion of macro ‘AES1’
 static const sph_u32 AES1[256] = {
                      ^~~~
../sha3/aes_helper.c:87:19: warning: ‘AES0_LE’ defined but not used [-Wunused-const-variable=]
 #define AES0      AES0_LE
                   ^
../sha3/aes_helper.c:122:22: note: in expansion of macro ‘AES0’
 static const sph_u32 AES0[256] = {
                      ^~~~
  CC(target) Release/obj.target/multihashing/sha3/sph_blake.o
  CC(target) Release/obj.target/multihashing/sha3/sph_bmw.o
  CC(target) Release/obj.target/multihashing/sha3/sph_cubehash.o
  CC(target) Release/obj.target/multihashing/sha3/sph_echo.o
  CC(target) Release/obj.target/multihashing/sha3/sph_groestl.o
  CC(target) Release/obj.target/multihashing/sha3/sph_jh.o
  CC(target) Release/obj.target/multihashing/sha3/sph_keccak.o
  CC(target) Release/obj.target/multihashing/sha3/sph_luffa.o
../sha3/sph_luffa.c:147:22: warning: ‘RC34’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC34[8] = {
                      ^~~~
../sha3/sph_luffa.c:140:22: warning: ‘RC30’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC30[8] = {
                      ^~~~
../sha3/sph_luffa.c:101:22: warning: ‘RC14’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC14[8] = {
                      ^~~~
../sha3/sph_luffa.c:94:22: warning: ‘RC10’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC10[8] = {
                      ^~~~
../sha3/sph_luffa.c:87:22: warning: ‘RC04’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC04[8] = {
                      ^~~~
../sha3/sph_luffa.c:80:22: warning: ‘RC00’ defined but not used [-Wunused-const-variable=]
 static const sph_u32 RC00[8] = {
                      ^~~~
  CC(target) Release/obj.target/multihashing/sha3/sph_shavite.o
  CC(target) Release/obj.target/multihashing/sha3/sph_simd.o
  CC(target) Release/obj.target/multihashing/sha3/sph_skein.o
  CC(target) Release/obj.target/multihashing/sha3/sph_whirlpool.o
  CC(target) Release/obj.target/multihashing/sha3/sph_shabal.o
  CC(target) Release/obj.target/multihashing/sha3/hamsi.o
  CC(target) Release/obj.target/multihashing/crypto/oaes_lib.o
../crypto/oaes_lib.c:30:19: warning: ‘_NR’ defined but not used [-Wunused-const-variable=]
 static const char _NR[] = {
                   ^~~
  CC(target) Release/obj.target/multihashing/crypto/c_keccak.o
  CC(target) Release/obj.target/multihashing/crypto/c_groestl.o
  CC(target) Release/obj.target/multihashing/crypto/c_blake256.o
  CC(target) Release/obj.target/multihashing/crypto/c_jh.o
  CC(target) Release/obj.target/multihashing/crypto/c_skein.o
  CC(target) Release/obj.target/multihashing/crypto/hash.o
  CC(target) Release/obj.target/multihashing/crypto/aesb.o
  CXX(target) Release/obj.target/multihashing/crypto/wild_keccak.o
In file included from ../crypto/wild_keccak.cpp:11:0:
../crypto/wild_keccak.h: In function ‘int crypto::keccak_generic(const uint8_t*, size_t, uint8_t*, size_t)’:
../crypto/wild_keccak.h:63:39: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
     rsiz = sizeof(state_t_m) == mdlen ? HASH_DATA_AREA : 200 - 2 * mdlen;
                  ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../crypto/wild_keccak.h: In function ‘int crypto::wild_keccak(const uint8_t*, size_t, uint8_t*, size_t, callback_t)’:
../crypto/wild_keccak.h:98:39: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
     rsiz = sizeof(state_t_m) == mdlen ? HASH_DATA_AREA : 200 - 2 * mdlen;
                  ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/multihashing.node
  COPY Release/multihashing.node
make: Leaving directory '/home/greg/pool/node_modules/multi-hashing/build'
multi-hashing@0.0.9 node_modules/multi-hashing
└── bindings@1.3.0
npm ERR! Linux 4.13.0-16-generic
npm ERR! argv "/home/greg/.nvm/v0.10.48/bin/node" "/home/greg/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/greg/pool/npm-debug.log

**Comment by tw4w3t** [comment]
Remove node_modules directly with rm-rf. From nvm change Node.Js version to 0.10.* and try again npm update.

**Comment by MyS5Droid** [comment]
I have same error, and using node 0.10.13 does not help...
There is an error inside of cryptonote-utils package. Until it is fixed this package will not install properly.

**@tw4w3t** please urge the package owner to fix the error and update the package repository so that the badly needed update gets to us
