### ISSUE TITLE
Errors when running "npm update"

### ISSUE THREAD

**Issue by jimbob4842** [electroneum/electroneum-pool#243]
```
thepsychoms@instance-2:~/pool$ npm update
\
> cryptonote-util@0.0.3 install /home/thepsychoms/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/home/thepsychoms/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
In file included from ../../nan/nan.h:199:0,
                 from ../src/main.cc:15:
../../nan/nan_maybe_pre_43_inl.h: In function ‘Nan::Maybe<bool> Nan::DefineOwnProperty(v8::Handle<v8::Object>, v8::Handle<v8::String>, v8::Handle<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_pre_43_inl.h:158:44: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
                  !(current & v8::ReadOnly) &&               // writable AND
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      !((attribs ^ current) & ~v8::ReadOnly) // same excluding RO
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<anonymous struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:111: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/thepsychoms/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/thepsychoms/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.9.0-5-amd64
gyp ERR! command "node" "/home/thepsychoms/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/thepsychoms/pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.9.0-5-amd64
npm ERR! argv "/home/thepsychoms/.nvm/v0.10.48/bin/node" "/home/thepsychoms/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! path /home/thepsychoms/pool/node_modules/multi-hashing/.travis.yml
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! Error: EACCES, unlink '/home/thepsychoms/pool/node_modules/multi-hashing/.travis.yml'
npm ERR!  { [Error: EACCES, unlink '/home/thepsychoms/pool/node_modules/multi-hashing/.travis.yml']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/thepsychoms/pool/node_modules/multi-hashing/.travis.yml' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/home/thepsychoms/pool/node_modules/multi-hashing/.travis.yml'
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/thepsychoms/pool/node_modules/multi-hashing/.travis.yml']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/thepsychoms/pool/node_modules/multi-hashing/.travis.yml' }
npm ERR! Linux 4.9.0-5-amd64
npm ERR! argv "/home/thepsychoms/.nvm/v0.10.48/bin/node" "/home/thepsychoms/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! path npm-debug.log.1090783356
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! Error: EACCES, open 'npm-debug.log.1090783356'
npm ERR!  { [Error: EACCES, open 'npm-debug.log.1090783356'] errno: 3, code: 'EACCES', path: 'npm-debug.log.1090783356' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/thepsychoms/pool/npm-debug.log

```

**Comment by Rndexspb** [comment]
sudo npm update

**Comment by jimbob4842** [comment]
```
instance-2:~/pool$ sudo npm update
sudo: npm: command not found
```

and when I run "sudo apt-get install npm"

```
instance-2:~/pool$ sudo apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package npm
```
