### ISSUE TITLE
EMFILE error

### ISSUE THREAD

**Issue by flashjpr** [electroneum/electroneum-pool#273]
Hi, 

We run https://etnmine.pro, and starting yesterday we have seen a big number of the following errors.
The server specs are: 4 AES_NI cpuss, 8 gigs of memory, and 80 GB of SSD. 

The pool module runs on 4 different threads. 

2018-04-06 11:43:54 [pool] (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
--

tail -25 pool_error.log
2018-04-06 11:44:17 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:44:18 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:44:44 (Thread 2) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:44:45 (Thread 2) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:44:46 (Thread 2) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:44:47 (Thread 2) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:44:55 (Thread 2) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:45:16 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:45:17 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:45:18 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:45:19 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:45:20 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:45:49 (Thread 3) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:45:50 (Thread 3) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:46:28 (Thread 1) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:46:47 (Thread 1) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:46:48 (Thread 1) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:46:49 (Thread 1) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:47:15 (Thread 2) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:47:42 (Thread 1) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:47:43 (Thread 1) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:48:10 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:48:11 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:48:12 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}
2018-04-06 11:48:13 (Thread 4) Error polling getblocktemplate {"code":"EMFILE","errno":"EMFILE","syscall":"connect"}

 tail -25 pool_crash.log
Error: bind EADDRINUSE
    at errnoException (net.js:905:11)
    at net.js:1085:30
    at Object.4:1 (cluster.js:594:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)

2018-04-01 05:40:51
Error: bind EADDRINUSE
    at errnoException (net.js:905:11)
    at net.js:1085:30
    at Object.4:1 (cluster.js:594:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)

Any help is being appreciated. Thankl

**Comment by flashjpr** [comment]
Moreover: 
lsof -i :3333 -> 23 connections
lsof -i :5555 -> 4002 connections
lsof -i :7777 -> 21 connections

**Comment by flashjpr** [comment]
They do, they all look clean. https://etnmine.pro/#pool_blocks 
Last block mined was 5mins ago. 
I suspect it's something to do with the max # of sockets open per port.

**Comment by flashjpr** [comment]
From a client side, the error is : 

SOCKET ERROR - [etnmine.pro:5555] RECEIVE error: socket closed
--
