### ISSUE TITLE
cryptonote-util build error (dependency)

### ISSUE THREAD

**Issue by MyS5Droid** [electroneum/electroneum-pool#284]
Hi

I have common build error inside cryptonote-util that I cannot find a fix to. It is preventing install/run proxy:
> cryptonote-util@0.0.3 install /home/xmrproxy/xmr-node-proxy/node_modules/cryptonote-util
> node-gyp rebuild
> 
> make: Entering directory '/home/xmrproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
>   CXX(target) Release/obj.target/cryptonote/src/main.o
>   CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
> ../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
> ../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
>    }
>    ^
>   CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
>   CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
> ../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
> ../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<anonymous struct> []’
>      return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
>                                                           ^
> cryptonote.target.mk:104: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
> make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
> make: Leaving directory '/home/xmrproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/home/xmrproxy/.nvm/v0.10.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
> gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
> gyp ERR! System Linux 4.9.0-6-amd64
> gyp ERR! command "node" "/home/xmrproxy/.nvm/v0.10.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/xmrproxy/xmr-node-proxy/node_modules/cryptonote-util
> gyp ERR! node -v v0.10.13
> gyp ERR! node-gyp -v v0.10.2
> gyp ERR! not ok 
> unbuild cryptonote-util@0.0.3
> npm WARN optional dep failed, continuing cryptonote-util@0.0.3
>

This is an error inside one of the dependancies, cryptonote-util v0.0.3 it prevents installation/startup of proxy

Please help thanks

**Comment by MyS5Droid** [comment]
wrong project O_o
