### ISSUE TITLE
Run init.js

### ISSUE THREAD

**Issue by GusevVasily** [electroneum/electroneum-pool#295]
Hello, what is a error?

**At first start everything is fine:**

2018-10-02 23:16:26 [master] Pool spawned on 4 thread(s)
(node:31710) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2018-10-02 23:16:26 [api] API started & listening on port 8117
2018-10-02 23:16:26 [payments] Started
2018-10-02 23:16:26 [payments] No workers' balances reached the minimum payment threshold
2018-10-02 23:16:26 [unlocker] Started
2018-10-02 23:16:26 [unlocker] No blocks candidates in redis
(node:31720) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:31718) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:31726) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2018-10-02 23:16:26 [api] Stat collection finished: 29 ms redis, 120 ms daemon
2018-10-02 23:16:26 [api] Broadcasting to 0 visitors and 0 address lookups
2018-10-02 23:16:26 [pool] (Thread 1) New block to mine at height 389847 w/ difficulty of 739280418683
2018-10-02 23:16:26 [pool] (Thread 1) Started server listening on port 5551
2018-10-02 23:16:26 [pool] (Thread 1) Started server listening on port 5552
2018-10-02 23:16:26 [pool] (Thread 1) Started server listening on port 5553
2018-10-02 23:16:26 [pool] (Thread 3) New block to mine at height 389847 w/ difficulty of 739280418683
2018-10-02 23:16:26 [pool] (Thread 3) Started server listening on port 5551
2018-10-02 23:16:26 [pool] (Thread 3) Started server listening on port 5552
2018-10-02 23:16:26 [pool] (Thread 3) Started server listening on port 5553
2018-10-02 23:16:26 [pool] (Thread 2) New block to mine at height 389847 w/ difficulty of 739280418683
2018-10-02 23:16:26 [pool] (Thread 2) Started server listening on port 5551
2018-10-02 23:16:26 [pool] (Thread 2) Started server listening on port 5552
2018-10-02 23:16:26 [pool] (Thread 2) Started server listening on port 5553
2018-10-02 23:16:26 [pool] (Thread 4) New block to mine at height 389847 w/ difficulty of 739280418683
2018-10-02 23:16:26 [pool] (Thread 4) Started server listening on port 5551
2018-10-02 23:16:26 [pool] (Thread 4) Started server listening on port 5552
2018-10-02 23:16:26 [pool] (Thread 4) Started server listening on port 5553
2018-10-02 23:16:29 [api] Stat collection finished: 1 ms redis, 98 ms daemon
2018-10-02 23:16:29 [api] Broadcasting to 0 visitors and 0 address lookups

**End errors:**

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

2018-10-02 23:16:31 [master] API died, spawning replacement...

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

2018-10-02 23:16:31 [master] Pool fork 1 died, spawning replacement worker...

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

2018-10-02 23:16:31 [master] Payment processor died, spawning replacement...

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

2018-10-02 23:16:31 [master] Block unlocker died, spawning replacement...

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

2018-10-02 23:16:31 [master] Pool fork 3 died, spawning replacement worker...
2018-10-02 23:16:31 [master] Pool fork 2 died, spawning replacement worker...

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.appendFile (fs.js:1191:14)
    at Timeout._onTimeout (/home/cryptonightetn/electroneum-pool/lib/logger.js:32:12)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

2018-10-02 23:16:31 [master] Pool fork 4 died, spawning replacement worker...

=======

Ubuntu: 16.04.05
NPM: 0.10.48
Redis: 3.0.6

Thanks..

**Comment by GusevVasily** [comment]
@electroneumRepo

**Comment by electroneumRepo** [comment]
Hi,

Can you confirm which version of node you have?

**Comment by electroneumRepo** [comment]
Hi,

Are you running as root?
How long after starting does this happen?

**Comment by GusevVasily** [comment]
@electroneumRepo
I don't know how to check the version of the script. But did git clone recently, ie, the latest version.

**Comment by GusevVasily** [comment]
No root. I create user.

5-8 sec after start script..

**Comment by GusevVasily** [comment]
https://dropmefiles.com/32qCw

It's video to start pool

**Comment by electroneumRepo** [comment]
^^ file was deleted due to error uploading.

Please can you share your config file. Appears something is wrong with logging module ...

**Comment by GusevVasily** [comment]
@electroneumRepo 
Config file:
http://rgho.st/private/7m55kxXcx/3ad0ba6f8666a4790688d9a8fd4d23f8

Video:
http://rgho.st/private/8dvzbLBrg/ab2935ce6728deac27a001d8532b4698

**Comment by electroneumRepo** [comment]
I've freshly cloned the repository and run `npm updated`, modified config and started the pool and do not seem to get this error.

One possible solution could be to modify the `lib/logger.js`

Changing `fs.appendFile(fileName, data);` to `fs.appendFileSync(fileName, data);` inside the setInterval function near the top of the file.

Please let me know if you can do this, if not I can create a patch for you. If it works please let me know and I'll push the change to master branch.

**Comment by GusevVasily** [comment]
@electroneumRepo 
It's a amazing! Good start script. Screenshot:
![screenshot_68](https://user-images.githubusercontent.com/21026700/46679126-f782ce80-cbee-11e8-9a81-574e88f5b058.png)

Thank you! <3

**Comment by GusevVasily** [comment]
Check screenshot

`
DeprecationWarning: Buffer() ...
`

What is it?

**Comment by electroneumRepo** [comment]
Are you sure that you are using node 0.10.48?

Can you confirm output for `su node -v` and also `su npm -v`

**Comment by GusevVasily** [comment]
Node: v10.10.0
NPM: 6.4.1

**Comment by electroneumRepo** [comment]
Ah, now this is what is causing you issues.

You need to be using node v0.10.48 to have the pool software work correctly.

Please refer to the README file for details on how to install node v0.10.48.

**Comment by GusevVasily** [comment]
@electroneumRepo 
Node: v0.10.48 (i change)
NPM: 2.15.1 (auto-change after `nvm install 0.10.48; nvm use 0.10.48`)

Screenshot:
![screenshot_69](https://user-images.githubusercontent.com/21026700/46680978-ed62cf00-cbf2-11e8-8c09-88c798a97d9f.png)

**Comment by electroneumRepo** [comment]
To ensure that you are using the correct version, first delete the node_modules folder inside the pool directory.

Then use `node -v` to ensure you are running node v0.10.48 and then run `npm update`.

Where you have used the newer version of node it's messed up the package hence the warnings above.

![image](https://user-images.githubusercontent.com/29386578/46681781-e41e3600-cbe3-11e8-96aa-1584cdd5fe3a.png)

I've done the setup all fresh and don't get the messages you are. Please do as above and see that the problem is resolved.

**Comment by GusevVasily** [comment]
Deleted the node_modules folder, change node version, made npm update. And now such mistakes:
![screenshot_70](https://user-images.githubusercontent.com/21026700/46682798-3d439500-cbf7-11e8-9c84-d864632edc86.png)

**Comment by GusevVasily** [comment]
It turns out that I run the script from another user, where the version of node 10.0, and root me and writes that the version 0.10.48
Write:
`root@froonex:~# su -c 'nvm install 0.10.48' cryptonightetn\                                                                  bash: nvm: command not found`

**Comment by GusevVasily** [comment]
And if you run it as root, there are no errors and warnings...

**Comment by GusevVasily** [comment]
@electroneumRepo

**Comment by electroneumRepo** [comment]
Firstly, You should not run as root user as this can cause other issues down the line.
Secondly, Using such a newer version of node.js is unsupported as some of dependencies require the older version.

Good luck with running your pool.

**Comment by GusevVasily** [comment]
Hello, @electroneumRepo 

1. I've run ASIC mining on the pool, but I don't see any statistics in the api. Have https://etn.spacepools.org/api/stats everything is fine, but I have:

![screenshot_159](https://user-images.githubusercontent.com/21026700/47662421-f4ef1580-dbab-11e8-946c-d1f8371044e5.png)

======================

![screenshot_160](https://user-images.githubusercontent.com/21026700/47662432-f8829c80-dbab-11e8-827c-ad6132acea34.png)

2. And another question. They have some kind of version v1.1.4, where they were able to take it, or they just modified?

3. How do I configure nginx proxy for mining correctly? My record:
![screenshot_161](https://user-images.githubusercontent.com/21026700/47662583-38498400-dbac-11e8-8196-6bd96d4cba74.png)

4. Can you tell me how to create several addresses in electronium-wallet-rpc? Function create_account / create_address do not exist in electronium, which is in monero.

Thanks.

**Comment by ghost** [comment]
Http://mibcoin.io coming to you the 15th Nov

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ghost** [comment]
@electroneumrepo

**Comment by ghost** [comment]
@electroneum check out my pool it works great .....
Tell Richard Ells

**Comment by GusevVasily** [comment]
@qanon1111 Don't litter, please, not on the matter.

**Comment by GusevVasily** [comment]
@electroneumRepo @electroneum Help, please for my issue 

> Hello, @electroneumRepo
> 
> 1. I've run ASIC mining on the pool, but I don't see any statistics in the api. Have https://etn.spacepools.org/api/stats everything is fine, but I have:
> 
> ![screenshot_159](https://user-images.githubusercontent.com/21026700/47662421-f4ef1580-dbab-11e8-946c-d1f8371044e5.png)
> 
> ======================
> 
> ![screenshot_160](https://user-images.githubusercontent.com/21026700/47662432-f8829c80-dbab-11e8-827c-ad6132acea34.png)
> 
> 1. And another question. They have some kind of version v1.1.4, where they were able to take it, or they just modified?
> 2. How do I configure nginx proxy for mining correctly? My record:
>    ![screenshot_161](https://user-images.githubusercontent.com/21026700/47662583-38498400-dbac-11e8-8196-6bd96d4cba74.png)
> 3. Can you tell me how to create several addresses in electronium-wallet-rpc? Function create_account / create_address do not exist in electronium, which is in monero.
> 
> Thanks.
