### ISSUE TITLE
Pool start fails to api??

### ISSUE THREAD

**Issue by icsugti** [electroneum/electroneum-pool#39]
Hi. I managed to install everything but I get this error:

`2017-11-14 14:17:10 [pool] (Thread 4) Started server listening on port 3333
2017-11-14 14:17:10 [pool] (Thread 4) Started server listening on port 5555
2017-11-14 14:17:10 [pool] (Thread 4) Started server listening on port 7777
2017-11-14 14:17:10 [pool] (Thread 1) New block to mine at height 24232 w/ difficulty of 7769391548
2017-11-14 14:17:10 [pool] (Thread 1) Started server listening on port 3333
2017-11-14 14:17:10 [pool] (Thread 1) Started server listening on port 5555
2017-11-14 14:17:10 [pool] (Thread 1) Started server listening on port 7777
2017-11-14 14:17:10 [pool] (Thread 2) New block to mine at height 24232 w/ difficulty of 7769391548
2017-11-14 14:17:10 [pool] (Thread 2) Started server listening on port 3333
2017-11-14 14:17:10 [pool] (Thread 2) Started server listening on port 5555
2017-11-14 14:17:10 [pool] (Thread 2) Started server listening on port 7777
2017-11-14 14:17:10 [pool] (Thread 3) New block to mine at height 24232 w/ difficulty of 7769391548
2017-11-14 14:17:10 [pool] (Thread 3) Started server listening on port 3333
2017-11-14 14:17:10 [pool] (Thread 3) Started server listening on port 5555
2017-11-14 14:17:10 [pool] (Thread 3) Started server listening on port 7777
2017-11-14 14:17:12 [charts] Started

TypeError: Cannot read property 'pool' of undefined
    at getPoolChartsData (/root/pool/lib/charts.js:211:39)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/root/pool/node_modules/async/dist/async.js:983:17)
    at /root/pool/node_modules/async/dist/async.js:958:16
    at /root/pool/node_modules/async/dist/async.js:3871:13
    at async.parallel.config (/root/pool/lib/api.js:127:13)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at /root/pool/node_modules/async/dist/async.js:1002:9

TypeError: Cannot read property 'pool' of undefined
    at getPoolChartsData (/root/pool/lib/charts.js:211:39)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/root/pool/node_modules/async/dist/async.js:983:17)
    at /root/pool/node_modules/async/dist/async.js:958:16
    at /root/pool/node_modules/async/dist/async.js:3871:13
    at async.parallel.config (/root/pool/lib/api.js:127:13)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at /root/pool/node_modules/async/dist/async.js:1002:9

2017-11-14 14:17:12 [master] API died, spawning replacement...
`

Some help??

**Comment by electroneumRepo** [comment]
I'm not 100% sure, but I would say some kind of configuration issue.

Could you post your config.json file?

**Comment by icsugti** [comment]
`{
    "coin": "electroneum",
    "symbol": "ETN",
    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },

        "console": {
            "level": "info",
            "colors": true
        }
    },
    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "etnkCG7SZ525rESy65AwWLZcyfF4z1w7s2PsKKq6WUjpdniUkVg5V7jUG4tyh18gKBARkiKmHneWSHiJk8pg7RL86fVtnNTCUs",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 2000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 10000,
                "desc": "High end hardware"
            }
        ],
        "varDiff": {
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "lastBlockCheckRate": 1
        }
    },
    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 10,
        "mixin": 0,
        "transferFee": 1,
        "minPayment": 5,
        "denomination": 100
    },
    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 20,
        "poolFee": 1.8,

        "coreDevDonation": 0.1
    },
    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 3,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "123nimeni"
    },
    "daemon": {
        "host": "127.0.0.1",
        "port": 26968
    },
    "wallet": {
        "host": "127.0.0.1",
        "port": 8082
    },
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null
    }
}



`


I really need help

**Comment by richardmadison** [comment]
Yeah we experienced something similar - our problem was the json file.  Try running it through https://jsonlint.com/ and it'll let you know if something isn't paired properly.

A couple of things to note - you should start your json with { and end it with } for jsonlint to like it.

Also, if you got your .json file from another repo (we got ours from cryptonote-forknote-pool github) there we're plenty of issues with nesting that we needed to resolve.

**Comment by richardmadison** [comment]
@icsugti it looks like github mangled your .json a bit - can you try to edit that?

**Comment by richardmadison** [comment]
@icsugti also you should remove your password from the .json (also change it in your live version...)

**Comment by icsugti** [comment]
Ok I pasted the code again , Valid Json... still got the same error...

`{
	"coin": "electroneum",
	"symbol": "ETN",
	"logging": {
		"files": {
			"level": "info",
			"directory": "logs",
			"flushInterval": 5
		},

		"console": {
			"level": "info",
			"colors": true
		}
	},
	"poolServer": {
		"enabled": true,
		"clusterForks": "auto",
		"poolAddress": "etnk2Hqs9pGEYKQc2RMbahUh6VCnXyVnriecZpvMHS6RYof4oiFsuMnBVxvTFMYkNQ7HWdxgeAdaqVo1LRThEJGu1CwNe3GuXy",
		"blockRefreshInterval": 1000,
		"minerTimeout": 900,
		"ports": [{
				"port": 3333,
				"difficulty": 100,
				"desc": "Low end hardware"
			},
			{
				"port": 5555,
				"difficulty": 2000,
				"desc": "Mid range hardware"
			},
			{
				"port": 7777,
				"difficulty": 10000,
				"desc": "High end hardware"
			}
		],
		"varDiff": {
			"minDiff": 2,
			"maxDiff": 100000,
			"targetTime": 100,
			"retargetTime": 30,
			"variancePercent": 30,
			"maxJump": 100
		},
		"shareTrust": {
			"enabled": true,
			"min": 10,
			"stepDown": 3,
			"threshold": 10,
			"penalty": 30
		},
		"banning": {
			"enabled": true,
			"time": 600,
			"invalidPercent": 25,
			"checkThreshold": 30
		},
		"slushMining": {
			"enabled": false,
			"weight": 300,
			"lastBlockCheckRate": 1
		}
	},
	"payments": {
		"enabled": true,
		"interval": 600,
		"maxAddresses": 10,
		"mixin": 0,
		"transferFee": 1,
		"minPayment": 10000,
		"denomination": 100
	},
	"blockUnlocker": {
		"enabled": true,
		"interval": 30,
		"depth": 20,
		"poolFee": 1.8,
		"devDonation": 0.1,
		"coreDevDonation": 0.1
	},
	"api": {
		"enabled": true,
		"hashrateWindow": 600,
		"updateInterval": 3,
		"port": 8117,
		"blocks": 30,
		"payments": 30,
		"password": "test"
	},
	"daemon": {
		"host": "127.0.0.1",
		"port": 26968
	},
	"wallet": {
		"host": "127.0.0.1",
		"port": 26969
	},
	"redis": {
		"host": "127.0.0.1",
		"port": 6379,
		"auth": null
	}
}`

**Comment by icsugti** [comment]
`root@endivo:~/pool# node init.js
2017-11-14 16:32:02 [master] Pool spawned on 4 thread(s)
2017-11-14 16:32:03 [unlocker] Started
2017-11-14 16:32:03 [unlocker] No blocks candidates in redis
2017-11-14 16:32:03 [payments] Started
2017-11-14 16:32:03 [payments] No workers' balances reached the minimum payment threshold
2017-11-14 16:32:03 [charts] Started

TypeError: Cannot read property 'pool' of undefined
    at getPoolChartsData (/root/pool/lib/charts.js:211:39)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/root/pool/node_modules/async/dist/async.js:983:17)
    at /root/pool/node_modules/async/dist/async.js:958:16
    at /root/pool/node_modules/async/dist/async.js:3871:13
    at async.parallel.config (/root/pool/lib/api.js:127:13)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at /root/pool/node_modules/async/dist/async.js:1002:9


TypeError: Cannot read property 'pool' of undefined
    at getPoolChartsData (/root/pool/lib/charts.js:211:39)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/root/pool/node_modules/async/dist/async.js:983:17)
    at /root/pool/node_modules/async/dist/async.js:958:16
    at /root/pool/node_modules/async/dist/async.js:3871:13
    at async.parallel.config (/root/pool/lib/api.js:127:13)
    at /root/pool/node_modules/async/dist/async.js:3866:24
    at replenish (/root/pool/node_modules/async/dist/async.js:998:17)
    at /root/pool/node_modules/async/dist/async.js:1002:9

2017-11-14 16:32:03 [master] API died, spawning replacement...
`

**Comment by icsugti** [comment]
Ok... I solved the problem by reinstall the pool , deleted the folder, upload it from git clone command again , npm update then all fine BUT!!! I've got another problem... the pool started, no error but the api doesn''t work... domain, added in confing + port 8117 but when I acces the port... nothing happnes, why? and the data for the site also doesnt work... still need some help !

**Comment by icsugti** [comment]
SOLVED!!! The firewall still blocked my ports so i forced to open from vesta control panel now 100% working... So for people who got the first problem... just rm -rf pool folder , git clone again from here, not other versions... and go for npm update then everything will e good!

**Comment by electroneumRepo** [comment]
Glad you got this sorted. I'll now close this issue.
