### ISSUE TITLE
nodejs version

### ISSUE THREAD

**Issue by rwalkos** [electroneum/electroneum-pool#46]
What version of node js is actually needed? I have v0.10.48 installed but when I do npm update I get many warnings such as:
```
../src/crypto/crypto.cpp: In function 'std::size_t crypto::rs_comm_size(std::size_t)':
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type 'crypto::rs_comm::<anonymous struct> []'
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:110: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/miner/pool/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.83-1-pve
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/miner/pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

// At the end:

npm ERR! Linux 4.4.83-1-pve
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryan/miner/pool/npm-debug.log

```

**Comment by electroneumRepo** [comment]
Hi,

Can you confirm that you have installed all of the main repo dependencies and the dependencies listed in the pool readme file.

If you have, please can you confirm which operating system you are using.

**Comment by rwalkos** [comment]
```
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety

$node --version
v0.10.48

$redis-server --version
Redis server v=2.6.17 sha=00000000:0 malloc=jemalloc-3.2.0 bits=64

build-essential is already the newest version (12.1ubuntu2).
cmake is already the newest version (3.5.2-2ubuntu1).
libunbound-dev is already the newest version (1.5.8-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
libboost-all-dev is already the newest version (1.61.0.2).
libssl-dev is already the newest version (1.0.2g-1ubuntu9.3).
```

**Comment by electroneumRepo** [comment]
Hi,

We have only tested the pool on Ubuntu 16.04. I would suggest that you try running on Ubuntu 16.04 rather than 16.10

**Comment by rwalkos** [comment]
Not sure if switching to Ubuntu 16.04 fixed my problem or everything I have learned trying to compile this helped when I started over but all seems to be working now. Thank you very much.

**Comment by electroneumRepo** [comment]
Glad you got it sorted.

If you want to add your pool to our pool list, submit a pull request with it added to the README file.
