### ISSUE TITLE
/home/mining/pool/lib/logger.js:23  throw e; ^  Error: EACCES: permission denied, mkdir 'logs'

### ISSUE THREAD

**Issue by bapparabi** [electroneum/electroneum-pool#55]
how to solve this error ??

mining@etn:~/pool$  node init.js
/home/mining/pool/lib/logger.js:23
        throw e;
        ^

Error: EACCES: permission denied, mkdir 'logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.<anonymous> (/home/mining/pool/lib/logger.js:20:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mining/pool/init.js:10:1)

**Comment by electroneumRepo** [comment]
Can you confirm which version of node.js you are using.

Support of this pool is for node 0.10.48

**Comment by bapparabi** [comment]
root@etn:~# npm -v
3.5.2
root@etn:~# node -v
v4.2.6
root@etn:~#

**Comment by electroneumRepo** [comment]
You need to install node 0.10.48. Please ensure you have followed all the [README](https://github.com/electroneum/electroneum-pool/blob/master/README.md) instructions.

Best way to install this is using [Node Version manager](https://github.com/creationix/nvm)
