### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cezarlacatus** [electroneum/electroneum-pool#6]
I get this error when I try npm update ; also redis and other dependencies are installed correctly only npn update doesn't work.Second thing is that I don't know where I should create that config.js with the pool ports and so on...I have skipped it...I had tried to run nodejs init.js and I get nothing(just showing as new line(.....also tried to connect with the browser but server didn't exist on my localhost(and reddis-server is running).How can I get this to work...also sorry for my bad englesh

npm update error:
> bignum@0.12.5 install /home/user/Desktop/pool/node_modules/bignum
> node-pre-gyp install --fallback-to-build

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})

> bignum@0.12.5 install /home/user/Desktop/pool/node_modules/base58-native/node_modules/bignum
> node-pre-gyp install --fallback-to-build

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings

> cryptonote-util@0.0.3 install /home/user/Desktop/pool/node_modules/cryptonote-util
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/Desktop/pool/node_modules/cryptonote-util
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by cezarlacatus** [comment]
I just had to make an config
