### ISSUE TITLE
example site, cant read API 

### ISSUE THREAD

**Issue by ghaffar47** [electroneum/electroneum-pool#73]
all the site do was those rolling circle.... if i try to direct from browser (127.0.0.1:8117) its return "invalid API request" can somebody help me

**Comment by electroneumRepo** [comment]
Hi,

Sounds like you don't have the API running or you don't have it configured correctly.

Please be sure to follow the README as that has the best explanation of what needs doing.

I would guess that the config file in the website directory needs editing to point to your api url.

**Comment by ghaffar47** [comment]
ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/makersmate/pool
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by electroneumRepo** [comment]
Hi,

You are not using the correct version of node.js

Please refer to the README

**Comment by ghaffar47** [comment]
thanks ill try again..

**Comment by electroneumRepo** [comment]
Closing due to inactivity
